dist: xenial
language: generic
addons:
  apt:
    packages:
    - cowsay
    - libio-pty-easy-perl
    - liburi-perl
    - python3-pip
    - python3-setuptools
install:
- python3 -m pip install httpolice
before_script:
- PATH+=:/usr/games
script:
- prove -v

# vim:ts=2 sts=2 sw=2 et
