#!/bin/sh

# Copyright © 2019 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
s="$@"
c=${#s}
a=$(printf "%0$((c+2))s" '' | tr ' ' '_')
b=$(printf "%0$((c+2))s" '' | tr ' ' '-')
w=$(printf "%0$((c+2))s" '')
cat <<EOF
 $a
< $s >
 $b
$w \\
$w  \\
$w   [ imagine there's a cow here ]
EOF

# vim:ts=4 sts=4 sw=4 et
