name: CI
on:
  push:
    branches-ignore:
    - '$**'
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install test deps
      run: |
        sudo apt-get install cowsay libio-pty-easy-perl liburi-perl
        python3 -m pip install httpolice
    - name: run tests
      run: |
        PATH+=:/usr/games
        prove -v
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
