name: CI
on:
  push:
    branches-ignore:
    - '$**'
  pull_request:
jobs:
  main:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install test deps
      run: |
        sudo apt-get install cowsay libio-pty-easy-perl liburi-perl
        python3 -m pip install httpolice
    - name: run tests
      run: |
        make test
      timeout-minutes: 1
    - name: install X test deps
      run: |
        sudo rm -rf /usr/share/zsh
        sudo apt-get install xvfb xterm xfonts-base tmux xdotool xclip bash mksh zsh
    - name: run X tests
      run: |
        make test-xvfb
      timeout-minutes: 1
    - name: check README syntax
      if: matrix.os != 'ubuntu-18.04'
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
